In [1]:
#Import the libraries
import numpy as np
import pandas as pd

In [2]:
#Read the dataset
data = pd.read_csv('GSE130817_RNA_seq_raw_counts.csv.gz')

In [3]:
file = data.to_csv()

In [4]:
#Drop na values
data.dropna(inplace=True)
data

Unnamed: 0  1_Day0_CAR19_RNA  2_Day0_CAR19_RNA  3_Day0_CAR19_RNA  \
0           N_unmapped           3630027           3797803           6180826   
1       N_multimapping           2046849           3567307           5150586   
2          N_noFeature           1426741           1977716           2533263   
3          N_ambiguous           1056343           1836591           2420097   
4      ENSG00000223972                 0                 0                 0   
...                ...               ...               ...               ...   
59909  ENSG00000278878                 0                 0                 0   
59910  ENSG00000263278                 0                 0                 0   
59911  ENSG00000280614                 0                 0                 0   
59912  ENSG00000281181                 0                 0                 0   
59913  ENSG00000280081                 0                11                 0   

       10_Day15_CAR19_RNA_WT  11_Day15_CAR19_RNA_WT  12_Day15_CAR19_RNA_WT  \
0                    3898814                7863049                6588285   
1                    4013907                5451898                6082790   
2                    2195695               13867788                3711809   
3                    1908986                2357681                3219869   
4                          0                      0                      0   
...                      ...                    ...                    ...   
59909                      0                      0                      0   
59910                      0                      0                      0   
59911                      0                      0                      0   
59912                      0                      0                      0   
59913                      0                      0                      0   

       13_Day15_CAR19_RNA_BID  14_Day15_CAR19_RNA_BID  15_Day15_CAR19_RNA_BID  
0                     2857836                 5761639                 3097916  
1                     3338395                 5704019                 3603698  
2                     1628551                 2443253                 2028724  
3                     1542531                 2679066                 1710727  
4                           0                       0                       0  
...                       ...                     ...                     ...  
59909                       0                       0                       0  
59910                       0                       0                       0  
59911                       0                       0                       0  
59912                       0                       0                       0  
59913                       0                       0                       0  

[59914 rows x 10 columns]

In [5]:
#Remove columns
gene = data['Unnamed: 0']
data.drop(['Unnamed: 0'],axis=1,inplace=True)
colo = data.columns

In [6]:
data

1_Day0_CAR19_RNA  2_Day0_CAR19_RNA  3_Day0_CAR19_RNA  \
0               3630027           3797803           6180826   
1               2046849           3567307           5150586   
2               1426741           1977716           2533263   
3               1056343           1836591           2420097   
4                     0                 0                 0   
...                 ...               ...               ...   
59909                 0                 0                 0   
59910                 0                 0                 0   
59911                 0                 0                 0   
59912                 0                 0                 0   
59913                 0                11                 0   

       10_Day15_CAR19_RNA_WT  11_Day15_CAR19_RNA_WT  12_Day15_CAR19_RNA_WT  \
0                    3898814                7863049                6588285   
1                    4013907                5451898                6082790   
2                    2195695               13867788                3711809   
3                    1908986                2357681                3219869   
4                          0                      0                      0   
...                      ...                    ...                    ...   
59909                      0                      0                      0   
59910                      0                      0                      0   
59911                      0                      0                      0   
59912                      0                      0                      0   
59913                      0                      0                      0   

       13_Day15_CAR19_RNA_BID  14_Day15_CAR19_RNA_BID  15_Day15_CAR19_RNA_BID  
0                     2857836                 5761639                 3097916  
1                     3338395                 5704019                 3603698  
2                     1628551                 2443253                 2028724  
3                     1542531                 2679066                 1710727  
4                           0                       0                       0  
...                       ...                     ...                     ...  
59909                       0                       0                       0  
59910                       0                       0                       0  
59911                       0                       0                       0  
59912                       0                       0                       0  
59913                       0                       0                       0  

[59914 rows x 9 columns]

In [7]:

data.sum()

1_Day0_CAR19_RNA          21794322
2_Day0_CAR19_RNA          34272997
3_Day0_CAR19_RNA          48003316
10_Day15_CAR19_RNA_WT     36794707
11_Day15_CAR19_RNA_WT     61086343
12_Day15_CAR19_RNA_WT     60757624
13_Day15_CAR19_RNA_BID    28355523
14_Day15_CAR19_RNA_BID    48675153
15_Day15_CAR19_RNA_BID    31434553
dtype: int64

In [8]:
#Calculate the cpm values from the data 
cpm = []
for i in range(0,len(data.columns)):
    tot = data.iloc[:,i].sum()
    count = (data.iloc[:,i]/tot)*10**6
    cpm.append(count)
    

In [9]:
cpm

[0        166558.381582
 1         93916.617365
 2         65463.885502
 3         48468.725019
 4             0.000000
              ...      
 59909         0.000000
 59910         0.000000
 59911         0.000000
 59912         0.000000
 59913         0.000000
 Name: 1_Day0_CAR19_RNA, Length: 59914, dtype: float64,
 0        110810.356036
 1        104085.061484
 2         57704.787241
 3         53587.114077
 4             0.000000
              ...      
 59909         0.000000
 59910         0.000000
 59911         0.000000
 59912         0.000000
 59913         0.320952
 Name: 2_Day0_CAR19_RNA, Length: 59914, dtype: float64,
 0        128758.313280
 1        107296.462603
 2         52772.666788
 3         50415.204650
 4             0.000000
              ...      
 59909         0.000000
 59910         0.000000
 59911         0.000000
 59912         0.000000
 59913         0.000000
 Name: 3_Day0_CAR19_RNA, Length: 59914, dtype: float64,
 0        105961.273180
 1        109089

In [10]:
#Convert cpm to an array
cpm = np.array(cpm)
cpm

array([[1.66558382e+05, 9.39166174e+04, 6.54638855e+04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.10810356e+05, 1.04085061e+05, 5.77047872e+04, ...,
        0.00000000e+00, 0.00000000e+00, 3.20952381e-01],
       [1.28758313e+05, 1.07296463e+05, 5.27726668e+04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.00785868e+05, 1.17733501e+05, 5.74332909e+04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.18369202e+05, 1.17185435e+05, 5.01950759e+04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.85512980e+04, 1.14641299e+05, 6.45380260e+04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [11]:
#Calculate the log values
log = np.log2(cpm+1)

In [12]:
log

array([[17.34567709, 16.51910819, 15.99843365, ...,  0.        ,
         0.        ,  0.        ],
       [16.75774621, 16.66741736, 15.81642839, ...,  0.        ,
         0.        ,  0.40157846],
       [16.97431726, 16.71125643, 15.68753061, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [16.62094815, 16.84517763, 15.80962473, ...,  0.        ,
         0.        ,  0.        ],
       [16.85294642, 16.83844606, 15.61528697, ...,  0.        ,
         0.        ,  0.        ],
       [16.58860189, 16.80677993, 15.97788419, ...,  0.        ,
         0.        ,  0.        ]])

In [13]:
log[1].max()

16.757746211940294

In [14]:
#Calculate zscore
import scipy.stats as stat
z=stat.zscore(log)
z

array([[ 2.28938482, -1.26561919, -0.08428159, ...,         nan,
                nan, -0.35355339],
       [-0.35716303, -0.14557119, -0.37473665, ...,         nan,
                nan,  2.82842712],
       [ 0.61772308,  0.18550656, -0.58043957, ...,         nan,
                nan, -0.35355339],
       ...,
       [-0.97295415,  1.19689488, -0.38559435, ...,         nan,
                nan, -0.35355339],
       [ 0.07137698,  1.1460573 , -0.69573037, ...,         nan,
                nan, -0.35355339],
       [-1.11855957,  0.906911  , -0.11707568, ...,         nan,
                nan, -0.35355339]])

In [15]:
#Convert to dataframe
df = pd.DataFrame(z).T
df = df.dropna(axis = 0)
df

0         1         2         3         4         5         6  \
0      2.289385 -0.357163  0.617723 -0.647755  0.615803 -0.497856 -0.972954   
1     -1.265619 -0.145571  0.185507  0.366049 -1.821023 -0.569205  1.196895   
2     -0.084282 -0.374737 -0.580440 -0.297472  2.778739 -0.243409 -0.385594   
3     -0.453870  0.504803 -0.077868  0.196018 -2.628981  0.398753  0.648517   
5     -0.353553 -0.353553  2.828427 -0.353553 -0.353553 -0.353553 -0.353553   
...         ...       ...       ...       ...       ...       ...       ...   
59892 -1.915772 -1.218459  0.301754 -0.643700  0.140348  0.242370  0.841420   
59895 -0.736761  0.511171 -0.473937  0.192786  2.314948 -1.084577 -0.100029   
59899 -0.840078  1.043850 -0.840078  0.785809  1.946622 -0.840078 -0.840078   
59904 -0.550231 -0.739537 -0.739537 -0.626384  0.296522 -0.602870  1.683801   
59913 -0.353553  2.828427 -0.353553 -0.353553 -0.353553 -0.353553 -0.353553   

              7         8  
0      0.071377 -1.118560  
1      1.146057  0.906911  
2     -0.695730 -0.117076  
3      0.760215  0.652413  
5     -0.353553 -0.353553  
...         ...       ...  
59892  1.032469  1.219570  
59895 -1.084577  0.460977  
59899 -0.753010  0.337041  
59904  1.885623 -0.607389  
59913 -0.353553 -0.353553  

[27728 rows x 9 columns]

In [21]:
ar = df.values
#Calculate the Variance of the Zscore
var = []
for i in range(0,len(z)):
    vari = ar[:,i].var()
    var.append(vari)
    

SyntaxError: invalid syntax (2451014176.py, line 5)

In [17]:
var

[0.942988007355724,
 0.8542750560462378,
 0.8831830847597055,
 0.8504379284850269,
 1.7534672925733845,
 0.8534036729255222,
 0.968850218276278,
 0.9032650151112669,
 0.9140187344756696]

In [18]:
#Creating a function to calculate the log value from the csv file
import numpy as np

def lg(var):
    try:
        data = pd.read_csv(var)
        data.dropna(inplace = True)
        numerics = ['int16', 'int32', 'int64']
        data = data.select_dtypes(include=numerics)
        cpm = []
        for i in range(0,len(data.columns)):
            tot = data.iloc[:,i].sum()
            count = (data.iloc[:,i]/tot)*10**6
            cpm.append(count)
        cpm = np.array(cpm)
        log = np.log2(cpm+1)
        return log
    except:
        print("Enter the correct csv file")
    

    

In [19]:
#Using the function
l = lg('GSE130817_RNA_seq_raw_counts.csv.gz')  
ld = pd.DataFrame(l).T
l

array([[17.34567709, 16.51910819, 15.99843365, ...,  0.        ,
         0.        ,  0.        ],
       [16.75774621, 16.66741736, 15.81642839, ...,  0.        ,
         0.        ,  0.40157846],
       [16.97431726, 16.71125643, 15.68753061, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [16.62094815, 16.84517763, 15.80962473, ...,  0.        ,
         0.        ,  0.        ],
       [16.85294642, 16.83844606, 15.61528697, ...,  0.        ,
         0.        ,  0.        ],
       [16.58860189, 16.80677993, 15.97788419, ...,  0.        ,
         0.        ,  0.        ]])

In [20]:
#Convert the log values into a RDS files
import pyreadr as prd
prd.write_rds("Lg.Rds", ld)
